
##PV creation 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
  labels: 15GB-for-home
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-075ba0995389c1a85

 