#Static provisioning is when you manually create a PersistentVolume and Kubernetes only
# binds PVCs to these pre-existing storage volumes, without creating them automatically.
---
## PV creation 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
  labels:
    purpose: ebs-static
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-09b0038e39c977d03
---
## PVC creation
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
## Pod attach to EBS volume
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static   # Required for Service selector match
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-static
---
## Service to expose NGINX
apiVersion: v1
kind: Service
metadata:
  name: nginx-ebs-static
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static   # MUST match Pod labels
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
