
##PV creation 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
  labels:
  purpose: size
spec:
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  labels: 
  purpose: size
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-075ba0995389c1a85
 