#create pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
#create pod
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: ebs-dynamic

#servcie
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007

#storage class will create pv & attach pvc to pod . this is the defination of dynamic provisioning in k8 volu
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
