apiVersion: v1
kind: Pod
metadata:
  name: mutli-container
  labels:
    purpose: mutli-container

spec:
  containers:
  - name: nginx
    image: nginx
  - name: redis
    image: redis:7
    ports:
      - containerPort: 6379
