apiVersion: v1
kind: Pod
metadata: 
  name: resource
spec:
  containers:
  - name: nginx
    image: nginx
    resource:
      requests: #to start container
        memory: "70Mi"
        cpu: "100m"
      limits:
        memory: "100Mi"
        cpu: "120m"  