apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: DevOpsTeamSize
      value: "10"
    - name: TeamLead
      value: "Anil"
