apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: nodeport-app
  ports:
    - port: 80         # Service Port
      targetPort: 80   # Pod Container Port
      nodePort: 30080  # NodePort (30000–32767 range)
